# -----------------------------------
# INSTRUÇÕES PARA USO LOCAL

# Inicie o container e entre no modo interativo:
# $ docker compose up -d; docker compose exec nodejs sh


# Parar e remover container após uso:
# $ docker container stop nodejs; docker container rm nodejs
# -----------------------------------

services:
    nodejs:
        image: docker.io/node:22-alpine
        container_name: nodejs
        volumes:
            - ../client:/client
        working_dir: /client
        command: sh -c "tail -f /dev/null"
        environment:
            - CHOKIDAR_USEPOLLING=true
        ports:
            - 8080:8080
