name: Deploy on GitHub Pages

on:
    workflow_run:
        workflows:
            -   Basic commit test
        types:
            -   completed

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    build:
        if: >
            github.event.workflow_run.conclusion == 'success' &&
            github.event.workflow_run.head_branch == 'main'

        runs-on: ubuntu-latest
        steps:
            -   name: Checkout files
                uses: actions/checkout@v4
                with:
                    sparse-checkout: client
                    sparse-checkout-cone-mode: true
                    path: .

            -   name: Move `client` folder files to `root`
                run: |
                    mv client/* .
                    rm -rf client

            -   name: Setup Node.js
                uses: actions/setup-node@v4
                with:
                    node-version: 22
                    cache: yarn

            -   name: Install dependencies
                run: yarn install

            -   name: Build project
                run: yarn build

            -   name: Upload artifact to GitHub Pages
                uses: actions/upload-pages-artifact@v4
                with:
                    path: dist/

    deploy:
        needs: build

        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        runs-on: ubuntu-latest
        steps:
            -   name: Deploy to GitHub Pages
                uses: actions/deploy-pages@v4
