name: Basic commit test

on:
    push:
        branches:
        -   '**'

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout files
                uses: actions/checkout@v4
                with:
                    sparse-checkout: client
                    sparse-checkout-cone-mode: true
                    path: .

            -   name: Move `client` folder files to `root`
                run: |
                    mv client/* .
                    rm -rf client

            -   name: Setup Node.js
                uses: actions/setup-node@v4
                with:
                    node-version: 22
                    cache: yarn

            -   name: Install dependencies
                run: yarn install

            -   name: Run linter
                run: yarn lint
